name: PR Review SLA and Slack Notifications

on:
  schedule:
    - cron: '0 9 * * *' # Executa diariamente às 9:00 UTC
  workflow_dispatch:

jobs:
  sla_check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @octokit/rest axios

      - name: Check PR review SLA and notify
        run: node path/to/your/script/check-pr-sla.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLA_HOURS: 48 # SLA em horas
