name: PR Review SLA and Slack Notifications

on:
  push:
    branches: [ "master" ]

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Notify Slack (starting)
        uses: act10ns/slack@v2
        with:
          status: starting
          channel: '#geral'
          message: Starting Docker Build image...
        if: always()

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn install -f MyWebApp/pom.xml

      - name: Notify Slack (status)
        uses: act10ns/slack@v2
        with:
          channel: '#geral'
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
        if: always()
